version: "3.8"
services: 
    frontend:
      build: "./docker/frontend"
      working_dir: "/src/ogp-frontend"
      command: "npm run dev"
      ports: 
        - "3000:3000"
      volumes: 
        - "./src:/src"

    backend:
        build: "./docker/backend"
        working_dir: "/src/ogp-backend"
        command: "php artisan serve --host 0.0.0.0 --port 8080"
        volumes: 
            - "./src:/src"
        ports: 
            - "8080:8080"
        depends_on: 
          - db

    db:
      image: "mysql"
      volumes: 
        - db_data:/var/lib/mysql
      ports: 
        - "3306:3306"
      environment: 
        MYSQL_DATABASE: "ogp"
        MYSQL_ROOT_PASSWORD: "password"
        TZ: "Asia/Tokyo"

    minio:
      image: "minio/minio"
      command: "minio server /data"
      volumes: 
        - "./resources/minio/data:/data"
      ports: 
        - "9000:9000"
      environment: 
        MINIO_ROOT_USER: "minio"
        MINIO_ROOT_PASSWORD: "password"

volumes: 
  db_data:
